name: 🔨 Build Kernel

on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch"
        required: true
        default: "A16"
        type: choice
        options:
          - A15
          
          
jobs:
  build:
    name: Build Kernel
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Install Dependencies
        run: |
          sudo apt update -y
          sudo apt install -y build-essential libncurses-dev bison flex libssl-dev libelf-dev dwarves bc rsync cpio python3 python3-pip git curl wget make lz4 zip unzip ccache
          sudo apt install -y fakeroot device-tree-compiler libdw-dev pkg-config lld llvm
          
      - name: 📥 Clone Kernel Source
        run: |
          git clone --depth=1 -b ${{ github.event.inputs.branch }} https://github.com/ZGSYet/NekoPoi-rebase.git kernel

      - name: 🔨 Build
        working-directory: kernel
        run: curl -LSs "https://raw.githubusercontent.com/Mr-Morat/KernelSU-Next/stable/kernel/setup.sh" | bash -s syscall && bash mk.sh
        
